import tkinter
from tkinter.constants import *
tk = tkinter.Tk()


frame = tkinter.Frame(tk, relief=GROOVE, bd=2, height=500, width=300)
frame.pack(fill=BOTH,expand=20)
label = tkinter.Label(frame, text="CALCULADORA", fg='yellow', font='Arial', bg='BLUE')
#label.pack(fill=X, expand=7)
label.place(bordermode=OUTSIDE, height=30, width=200, x=50)
button1 = tkinter.Button(frame,text="1")
button2 = tkinter.Button(frame,text="2")
button3 = tkinter.Button(frame,text="3")
button4 = tkinter.Button(frame,text="4")
button5 = tkinter.Button(frame,text="5")
button6 = tkinter.Button(frame,text="6")
button7 = tkinter.Button(frame,text="7")
button8 = tkinter.Button(frame,text="8")
button9 = tkinter.Button(frame,text="9")
button0 = tkinter.Button(frame,text="0")
button1.place(bordermode=OUTSIDE, height=40, width=40, y=70)
button2.place(bordermode=OUTSIDE, height=40, width=40, y=70, x=50)
button3.place(bordermode=OUTSIDE, height=40, width=40, y=70, x=100)
button4.place(bordermode=OUTSIDE, height=40, width=40, y=120)
button5.place(bordermode=OUTSIDE, height=40, width=40, y=120, x=50)
button6.place(bordermode=OUTSIDE, height=40, width=40, y=120, x=100)
button7.place(bordermode=OUTSIDE, height=40, width=40, y=170)
button8.place(bordermode=OUTSIDE, height=40, width=40, y=170, x=50)
button9.place(bordermode=OUTSIDE, height=40, width=40, y=170, x=100)
button0.place(bordermode=OUTSIDE, height=40, width=40, y=220, x=50)
tk.mainloop()